version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./"5.Project Development Phase":/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
