services:
  - type: web
    name: credit-card-approval
    env: python
    buildCommand: pip install -r "5.Project Development Phase/requirements.txt"
    startCommand: gunicorn app:app --chdir "5.Project Development Phase"
