services:
  - type: web
    name: credit-card-approval
    env: python
    buildCommand: cd "5.Project Development Phase" && pip install -r requirements.txt
    startCommand: cd "5.Project Development Phase" && gunicorn app:app
